name: E2E TESTS

on: [push, pull_request]

jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug     

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or '18.20.0' minimum

      - name: NPM install
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Playwright install
        run: npx playwright install --with-deps

      - name: Install @wordpress/env
        run: npm install -g @wordpress/env

      - name: Start WordPress
        run: |
          # Start test environment
          wp-env start
          npx wait-on http://localhost:8889 -t 60000

      - name: Install GatherPress from GitHub
        run: npx wp-env run cli -- wp plugin install https://github.com/gatherpress/gatherpress/archive/refs/heads/main.zip --activate
    

      - name: Run Playwright Tests
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WP_BASE_URL: 'http://localhost:8889'
          PLAYWRIGHT_DEBUG: '1'
        run: npm run test:e2e 

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Stop WordPress
        if: always()
        run: wp-env stop