name: E2E TESTS

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start WordPress via wp-env
        run: npx wp-env start &
        
      - name: Wait for WordPress to boot
        run: |
          echo "Waiting for WordPress..."
          until curl -s http://localhost:8888/wp-login.php; do
            sleep 2
          done
          echo "WordPress is ready."

      - name: Run tests
        run: npx playwright test

      - name: Stop wp-env
        if: always()
        run: npx wp-env stop
